### ISSUE TITLE
About "learnable prior"

### ISSUE THREAD

**Issue by WCUSTC** [hongyliu/CLRNet#2]
作者说prior是可学习的参数，x,y,theta三个参数决定一个prior。

我读了您的代码，似乎不是按照可学习prior来实现的。求解惑~

**Comment by hongyliu** [comment]
我个人的理解是，模型将会输出多个lane prior为结果，和作为ground truth的lane prior一起计算loss，这样作为结果的一部分，x、y、theta可以在学习过程中进行数值调整
根据文中3.1的描述
![image](https://user-images.githubusercontent.com/52653305/166915771-fc2ee695-57be-454d-99bc-e376f1727460.png)
设计输出为L*（2+1+3+72），其中L表示得到的lane个数，2为（1）中提到的前背景概率，1为（2）中有效点个数即lane长度，3为（3）中x、y、theta，72为（4）中设定的每条lane点的个数
（属于我个人推理，由于我现在还没有达到原文的效果，所以仅供参考）

**Comment by WCUSTC** [comment]
你目前tusimple和culane上结果多少啊？
我跑了你的代码，效率很慢，是我哪里弄错了吗？

**Comment by WCUSTC** [comment]
![图片](https://user-images.githubusercontent.com/33274620/166920447-4a70dfd8-0386-4999-a453-424825398c95.png)
作者的回答

**Comment by hongyliu** [comment]
从作者的说法来看我这个想法应该是错了，估计在roigather这部分不太可靠，因为一些设想都是基于lane prior的结构得到的
我现在只在tusimple上试了，结果在50左右不太理想，至于速度问题我想还是有待优化的，现在我单卡跑耗时也很长
如果作者能尽快把代码release就好了 : (

**Comment by WCUSTC** [comment]
> 从作者的说法来看我这个想法应该是错了，估计在roigather这部分不太可靠，因为一些设想都是基于lane prior的结构得到的 我现在只在tusimple上试了，结果在50左右不太理想，至于速度问题我想还是有待优化的，现在我单卡跑耗时也很长 如果作者能尽快把代码release就好了 : (

作者的做法应该类似sparse rcnn，关键我不懂sparse rcnn。所以复现起来特别吃力。我现在很痛苦

**Comment by WCUSTC** [comment]
作者已释放代码

**Comment by hongyliu** [comment]
好的，感谢通知！
